title: Changzhen Wang
description: Focus on GIS Development and Application
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  home_url: https://smartwang18.github.io/Changzhen/
  project_url: https://smartwang18.github.io/Changzhen/project
  publication_url: https://smartwang18.github.io/Changzhen/publication
  award_url: https://smartwang18.github.io/Changzhen/award
  hobby_url: https://smartwang18.github.io/Changzhen/hobby
 
