title: Changzhen Wang
description: I'm looking for PhD position related to GIS
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  home_url: https://smartwang18.github.io/Changzhen/
  project_url: https://smartwang18.github.io/Changzhen/project
  publication_url: https://smartwang18.github.io/Changzhen/publication
 
